<a href="https://colab.research.google.com/github/globalaihub/introduction-to-machine-learning/blob/main/Linear%20Algebra/Linear_Algebra.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

![](img/logo.png)

<h5><center>All rights reserved ©️ Global AI Hub 2020</center></h5> 

# Linear Algebra Review

![](img/linear.png)

- **Scalar:**  Any single numerical value.
- **Vector:** An array of numbers(data) is a vector. 
- **Matrix:** A matrix is a 2-D array of shape $(m×n)$ with m rows and n columns.
- **Tensor:** Generally, an n-dimensional array where n>2 is called a Tensor. But a matrix or a vector is also a valid tensor.

![](img/conv_rgb.png)

In [1]:
import numpy as np

### Creating Vector

In [2]:
arr_1 = np.array([1,2,3,4,5],ndmin=2)
arr_1

array([[1, 2, 3, 4, 5]])

In [3]:
print(f"Type: {type(arr_1)}")
print(f"Shape: {arr_1.shape}")
print(f"Dimension: {arr_1.ndim}")

Type: <class 'numpy.ndarray'>
Shape: (1, 5)
Dimension: 2


### Creating Matrix

In [5]:
arr_2 = np.array([[1,2,3,4],
                  [5,6,7,8]]) 
arr_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
print(f"Type: {type(arr_2)}")
print(f"Shape: {arr_2.shape}")
print(f"Dimension: {arr_2.ndim}")

Type: <class 'numpy.ndarray'>
Shape: (2, 4)
Dimension: 2


In [12]:
#Array with full 0's
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [13]:
#Array with full 1's
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
#Array with ones on the diagonal and zeros elsewhere
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
#Return evenly spaced values within a given interval.
np.arange(0, 10, 1) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#Return evenly spaced numbers over a specified interval
np.linspace(2, 3, 5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [11]:
np.random.randint(5, 10, size= (4,4))

array([[9, 9, 5, 6],
       [8, 8, 6, 5],
       [7, 7, 6, 9],
       [8, 8, 9, 9]])

# Addition and Scalar Multiplication 

## Addition

 Two matrices may be added or subtracted only if they have the same dimension ( $ m_1$ x $n_1$ = $m_2$  x $n_2$ ); that is, they must have the same number of rows and columns. Addition or subtraction is accomplished by adding or subtracting corresponding elements.



In [7]:
matrice_1 = np.array([[1, 2, 3, 4], 
                      [5, 6, 7, 8], 
                      [9, 8, 6, 5]])

matrice_2 = np.array([[-1, 4, 3, 5],
                      [1, 4, 7, 9],
                      [-6, 5, 11, -4]])

print(f"Matrice_1: \n{matrice_1}","\n")
print(f"Shape of Matrice 1: {matrice_1.shape}")
print(f"\nMatrice_2: \n{matrice_2}","\n")
print(f"Shape of Matrice 2: {matrice_2.shape}")

Matrice_1: 
[[1 2 3 4]
 [5 6 7 8]
 [9 8 6 5]] 

Shape of Matrice 1: (3, 4)

Matrice_2: 
[[-1  4  3  5]
 [ 1  4  7  9]
 [-6  5 11 -4]] 

Shape of Matrice 2: (3, 4)


### Adding two matrices

In [8]:
matrice_1 + matrice_2

array([[ 0,  6,  6,  9],
       [ 6, 10, 14, 17],
       [ 3, 13, 17,  1]])

In [9]:
matrice_1 - matrice_2

array([[ 2, -2,  0, -1],
       [ 4,  2,  0, -1],
       [15,  3, -5,  9]])

---

## Stacking

In [5]:
st1 = np.array([[1,2,3],
                [4,5,6]])

st2 = np.array([[6,5,4], 
                [3,2,1]])
print(st1)
print(st2)

[[1 2 3]
 [4 5 6]]
[[6 5 4]
 [3 2 1]]


In [7]:
np.vstack((st1,st2)) #vertical stacking

array([[1, 2, 3],
       [4, 5, 6],
       [6, 5, 4],
       [3, 2, 1]])

In [8]:
np.hstack((st1,st2)) #vertical stacking

array([[1, 2, 3, 6, 5, 4],
       [4, 5, 6, 3, 2, 1]])

## Multiplication

### Scalar Multiplication

 The term scalar multiplication refers to the product of a real number and a matrix. In scalar multiplication, each entry in the matrix is multiplied by the given scalar.

In [11]:
matrice3 = matrice_1 * matrice_2
matrice3

array([[ -1,   8,   9,  20],
       [  5,  24,  49,  72],
       [-54,  40,  66, -20]])

### Matrix-Vector Multiplication 

 Multiplication between a matrix "M" and a vector "v", we need to view the vector as a column matrix. We define the matrix-vector product only for the case when the number of columns in M equals the number of rows in v. So, if M is an m×n matrix (i.e., with n columns), then the product $M.v$ is defined for $n$ × $1$ column vectors x. If we let $M.v=r$, then $r$ is an $m$ x $1$ column vector. 

 $$ (m\;,\;n)\;\;.\;(n\;,\;1) = (m\;,\;1) $$

In [13]:
M = np.array([[ 6, 1 ,3], 
              [ -1, 1 ,1], 
              [ 1, 3 ,2]])

#Rank 1 array
v = np.array([1, 2, 3])

print(f"Shape of matrix M = {M.shape}","\n",f"Shape of vector v = {v.shape}")

Shape of matrix M = (3, 3) 
 Shape of vector v = (3,)


#### Option 1:

In [11]:
6*1 + 1*2 + 3*3

17

In [14]:
M.dot(v)

array([17,  4, 13])

#### Option 2:

In [12]:
np.dot(M,v)

array([17,  4, 13])

### Matrix-Matrix Multiplication 

Matrix-Matrix multiplication,  the number of columns in the first matrix must be equal to the number of rows in the second matrix. The resulting matrix, known as the matrix product, has the number of rows of the first and the number of columns of the second matrix.

$$ n_1 = m_2$$


In [14]:
db = np.array([[-1, 4, 3, 5],
              [1, 4, 7, 9],
              [-6, 5, 11, -4]])


In [16]:
C = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 8, 6, 5]])

D = np.array([[-1, 4, 3, 5],
              [1, 4, 7, 9],
              [-6, 5, 11, -4]]).reshape(4,3)

print(f"Shape of matrix C = {C.shape}","\n",f"Shape of matrix D = {D.shape}")
print(D)

Shape of matrix C = (3, 4) 
 Shape of matrix D = (4, 3)
[[-1  4  3]
 [ 5  1  4]
 [ 7  9 -6]
 [ 5 11 -4]]


In [17]:
C.dot(D)

array([[ 50,  77, -23],
       [114, 177, -35],
       [ 98, 153,   3]])

In [18]:
np.dot(C,D)

array([[ 50,  77, -23],
       [114, 177, -35],
       [ 98, 153,   3]])

In [19]:
np.dot(D,C)

array([[46, 46, 43, 43],
       [46, 48, 46, 48],
       [-2, 20, 48, 70],
       [24, 44, 68, 88]])

## Matrix Multiplication Properties

1. The commutative property of multiplication $AB \neq BA$

2. Associative property of multiplication     $(AB)C =  A(BC)$

3. Distributive properties                    $A(B+C) =  AB+AC$

4. Multiplicative identity property           $ IA =A\, \& \,  AI=A$

5. Multiplicative property of zero            $ I0 =0  \, \&  \,  A0=0$

6. Dimension property

# Inverse and Transpose

## Inverse

In linear algebra, an n-by-n square matrix A is called invertible (also nonsingular or nondegenerate), if there exists an n-by-n square matrix B such that

$ AB=BA=I $ where In denotes the n-by-n identity matrix and the multiplication used is ordinary matrix multiplication. If this is the case, then the matrix B is uniquely determined by A, and is called the (multiplicative) inverse of A, denoted by A−1.

 $$A\;.\; A^{-1} = I $$
Where:  
$I$: Identity Matrix  
Shape A: $ (n,n)$ 

In [18]:
#Example of identity matrix with 3 x 3 dimension
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
x = np.array([[6, 9],
              [12, 17]])

y = np.array([[8, 5],
              [1, 2]])

In [21]:
x_inv = np.linalg.inv(x)
x_inv

array([[-2.83333333,  1.5       ],
       [ 2.        , -1.        ]])

In [23]:
x.dot(x_inv)

array([[1., 0.],
       [0., 1.]])

In [24]:
a = np.array([[6, 9 ,13],
              [12, 17 ,10],
              [4,12,5]])

a_inv = np.linalg.inv(a)
a_inv

array([[-0.05852843,  0.18561873, -0.21906355],
       [-0.03344482, -0.0367893 ,  0.16053512],
       [ 0.1270903 , -0.06020067, -0.01003344]])

In [25]:
np.dot(a,a_inv)

array([[ 1.00000000e+00, -7.63278329e-17, -9.02056208e-17],
       [-5.55111512e-17,  1.00000000e+00, -6.93889390e-17],
       [-2.77555756e-17,  3.46944695e-17,  1.00000000e+00]])

## Transpose

In linear algebra, the transpose of a matrix is an operator which flips a matrix over its diagonal; that is, it switches the row and column indices of the matrix $A$ by producing another matrix, often denoted by $A^T$(among other notations).

If matrix A's shape is $(n,m)$, then shape of $A^T$ will be shape of $(m,n)$

In [22]:
x

array([[ 6,  9],
       [12, 17]])

In [23]:
x_trans = x.T
x_trans

array([[ 6, 12],
       [ 9, 17]])

In [37]:
A = np.random.randint(1, 10, size=(5, 3))

print(f"Matrice: \n{A}")
print(f"\nShape: {A.shape}")

Matrice: 
[[4 3 1]
 [5 2 7]
 [7 9 4]
 [1 8 9]
 [8 6 1]]

Shape: (5, 3)


In [49]:
## Seed
np.random.seed(12)

A = np.random.randint(1, 10, size=(5, 3))

print(f"Matrice: \n{A}")
print(f"\nShape: {A.shape}")

Matrice: 
[[7 2 3]
 [4 4 1]
 [7 2 5]
 [6 3 7]
 [1 6 9]]

Shape: (5, 3)


In [82]:
np.random.seed(123)

A = np.random.randint(1, 10, size=(5, 3))

B = np.random.randint(17, 100, size=(5, 3))

print(A)
print(B)
A + B

[[3 3 7]
 [2 4 7]
 [2 1 2]
 [1 1 4]
 [5 1 1]]
[[85 66 72]
 [84 19 56]
 [83 64 78]
 [65 24 69]
 [44 51 93]]


array([[88, 69, 79],
       [86, 23, 63],
       [85, 65, 80],
       [66, 25, 73],
       [49, 52, 94]])

In [83]:
A_t = A.T

print(f"Matrice:  \n{A_t}")
print(f"\nShape: {A_t.shape}")

Matrice:  
[[3 2 2 1 5]
 [3 4 1 1 1]
 [7 7 2 4 1]]

Shape: (3, 5)
